language: ruby
rvm:
    - 2.4.0
    - 2.3.3
    - 2.3.0
env:
    global:
        - TRAVIS_NODE_VERSION="7.6"
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
    - npm install -g yarn
script:
    - yarn install
    - yarn run lint
    - yarn run build
    # - rake test
# Travis runs rake test automatically
sudo: false
