language: ruby
rvm:
    - 2.4.0
    - 2.3.3
    - 2.3.0
env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
    - npm install
script:
    - npm run lint
    - npm run build
    # - rake test
# Travis runs rake test automatically
sudo: false
